setup: &setup
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *setup
  database: badge_development
  username: postgres
  password:

production:
  <<: *setup
  database: badge_production
  username: badge_production_user
  password: badge_production_password

staging:
  <<: *setup
  database: badge_staging
  username: badge_staging_user
  password: badge_staging_password

test:
  <<: *setup
  host: 127.0.0.1
  database: badge_test
  username: postgres
  password:
